defaultPath: &defaultpath /metrics
job: &job node-exporter

serviceMonitors:
  - name: smig-inference-gpu
    port: 9400
    host: smig-inference.lab.smig.tech
    customPath: *defaultpath
    job: "gpu"

  - name: smig-inference-node-exporter
    port: 9100
    host: smig-inference.lab.smig.tech
    customPath: *defaultpath
    job: *job
