apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cluster-ca-issuer
    external-dns.alpha.kubernetes.io/target: k3s.lab.smig.tech.
  name: rabbitmq
  namespace: bootdev
spec:
  rules:
  - host: bootdev-rmq.lab.smig.tech
    http:
      paths:
      - backend:
          service:
            name: bootdev
            port:
              number: 15672
        path: /
        pathType: Exact
  tls:
  - hosts:
    - bootdev-rmq.lab.smig.tech
    secretName: bootdev-rmq-tls
status:
  loadBalancer: {}
