apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: home-assistant-homekit
  labels:
    app.kubernetes.io/component: homekit-bridge
spec:
  entryPoints:
    - homekit
  routes:
    - match: HostSNI(`*`)
      services:
        - name: home-assistant-homekit
          port: 21063
