resources:
  - deployment.yaml
  - service.yaml
  - service-homekit.yaml
  - ingress.yaml
  - ingressroute-tcp.yaml
  - udproute.yaml
  - service-mdns.yaml

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: stable@sha256:9a5a3eb4a213dfb25932dee9dc6815c9305f78cecb5afa716fa2483163d8fb5b

configMapGenerator:
  - name: home-assistant-config
    behavior: create
    envs:
      - config.env

generatorOptions:
  disableNameSuffixHash: false

commonLabels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/part-of: home-automation
