resources:
  - deployment.yaml
  - service.yaml
  - service-homekit.yaml
  - ingress.yaml
  - ingressroute-tcp.yaml
  - udproute.yaml
  - service-mdns.yaml

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: stable@sha256:3007eeeaf87d1e3a2047faeac6ff01dfef218b8a404bdff3ce421c1f4f363a43

configMapGenerator:
  - name: home-assistant-config
    behavior: create
    envs:
      - config.env

generatorOptions:
  disableNameSuffixHash: false

commonLabels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/part-of: home-automation
