apiVersion: v1
kind: Service
metadata:
  name: home-assistant-mdns
  labels:
    app.kubernetes.io/component: mdns
spec:
  type: ClusterIP
  ports:
    - port: 5353
      targetPort: mdns
      protocol: UDP
      name: mdns
  selector:
    app.kubernetes.io/name: home-assistant
