---
apiVersion: v1
kind: Secret
metadata:
  name: renovate-secrets
  namespace: renovate
  annotations:
    avp.kubernetes.io/path: "k8s/data/renovate-bot/config"
    avp.kubernetes.io/secret-version: "4"
type: Opaque
data:
  RENOVATE_TOKEN: <gitea_token>
  GITHUB_TOKEN: <github_token>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |-
    {
      "repositories": ["smiggiddy/argocd", "smiggiddy/oci_docker"],
      "endpoint": "https://gitea.smigz.com",
      "argocd": {
      "fileMatch": ["apps/.+\\.yaml$"]
    }
      }

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: renovate/renovate:full
              name: renovate-bot
              env:
                - name: RENOVATE_PLATFORM
                  value: "gitea"
                - name: GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-secrets
                      key: GITHUB_TOKEN
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-secrets
                      key: RENOVATE_TOKEN
                - name: RENOVATE_AUTODISCOVER
                  value: "true"
                - name: RENOVATE_BASE_DIR
                  value: "/tmp/renovate/"
                - name: RENOVATE_CONFIG_FILE
                  value: "/opt/renovate/config.json"
                - name: LOG_LEVEL
                  value: debug
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
