apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perplexica
  annotations:
    cert-manager.io/cluster-issuer: cluster-ca-issuer
    external-dns.alpha.kubernetes.io/target: k3s.lab.smig.tech.
spec:
  tls:
    - hosts:
        - perplexica.lab.smig.tech
      secretName: perplexica-tls
  rules:
    - host: perplexica.lab.smig.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: perplexica
                port:
                  name: http
