{{- range .Values.serviceMonitors }}
---
apiVersion: v1
kind: Service
metadata:
  name: ext-{{ .name }}
  labels:
    app: ext-{{ .name }}
    external-prometheus: "true"
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .port }}
  type: ExternalName
  externalName: {{ .host }}
{{- end }}
